[package]
name = "pf_accel"
version = "0.1.0"
edition = "2021"

[lib]
name = "_pf_accel"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }

[profile.release]
lto = true
codegen-units = 1
